(dp1
S'output'
p2
S"<type 'exceptions.SyntaxError'> invalid select attribute: nome"
p3
sS'layer'
p4
S'/home/amauri/web2py/applications/Torneio/controllers/funcoes.py'
p5
sS'code'
p6
S'def atualiza_pontos():\n\tdados = db(CLUBES).select(nome="Palmeiras")\n\tprint dados\n\n\nresponse._vars=response._caller(atualiza_pontos)\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/amauri/web2py/gluon/restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "/home/amauri/web2py/applications/Torneio/controllers/funcoes.py", line 6, in <module>\n  File "/home/amauri/web2py/gluon/globals.py", line 417, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/amauri/web2py/applications/Torneio/controllers/funcoes.py", line 2, in atualiza_pontos\n    dados = db(CLUBES).select(nome="Palmeiras")\n  File "/home/amauri/web2py/gluon/packages/dal/pydal/objects.py", line 2020, in select\n    return adapter.select(self.query, fields, attributes)\n  File "/home/amauri/web2py/gluon/packages/dal/pydal/adapters/sqlite.py", line 123, in select\n    return super(SQLiteAdapter, self).select(query, fields, attributes)\n  File "/home/amauri/web2py/gluon/packages/dal/pydal/adapters/base.py", line 1283, in select\n    sql = self._select(query, fields, attributes)\n  File "/home/amauri/web2py/gluon/packages/dal/pydal/adapters/base.py", line 1091, in _select\n    raise SyntaxError(\'invalid select attribute: %s\' % key)\nSyntaxError: invalid select attribute: nome\n'
p11
s.